version: '3.8'

services:
  nginx:
    build: .
    image: walquiriamourao/devops-nginx-php-php:nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    build: ./php
    image: walquiriamourao/devops-nginx-php-php:php
    container_name: php
    volumes:
      - ./html:/var/www/html
    expose:
      - "9000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-data/seed_users.sql:/docker-entrypoint-initdb.d/seed_users.sql
