name: Deploy to ECS Fargate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Altere para sua região

      - name: Build and push Docker image to ECR
        env:
          ECR_REPOSITORY: devops-nginx-php
          IMAGE_TAG: latest
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin <ID_DA_SUA_CONTA>.dkr.ecr.us-east-2.amazonaws.com
          docker build -t $ECR_REPOSITORY .
          docker tag $ECR_REPOSITORY:latest <ID_DA_SUA_CONTA>.dkr.ecr.us-east-2.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          docker push <ID_DA_SUA_CONTA>.dkr.ecr.us-east-2.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster seu-cluster --service seu-service --force-new-deployment
